INSERT INTO  Producto VALUES
(NULL,'Aceite La Favorita','500 ml',3.5,1500,'/OnlineShop/products-images/aceite_la_favorita.jpg','La Favorita','Aceite de cocina hecho a base de Palma'),
(NULL,'Aceite Alesol','350 ml',2.0,2000,'/OnlineShop/products-images/aceite-alesol.jpg','Alesol','Aceite de cocina extraído de la Palma Ecuatoriana'),
(NULL,'Aceite Oli','750 ml',5.5,500,'/OnlineShop/products-images/aceite-oli.jpg','Oli','Aceite de cocina hecho a base de oliva'),
(NULL,'Ají de Maracuyá Olé','155 gr',2.5,1500,'/OnlineShop/products-images/aji-maracuya.jpg','Olé','Ají sazonado con maracuyá para un toque agriducle'),
(NULL,'Atún Isabel','350 gr',1.6,2000,'/OnlineShop/products-images/atun-isabel.jpg','Isabel','Atún rebanado bañado en aceite de girasol'),
(NULL,'Atún Mr. Fish','175 gr',1.5,2000,'/OnlineShop/products-images/atun-mr-fish.jpg','Mr. Fish','Atún rebanado bañado en aceite de girasol'),
(NULL,'Atún Real','180 gr',1.2,2000,'/OnlineShop/products-images/atun-real.webp','Real','Atún rabanado bañado en aceite de girasol'),
(NULL,'Azúcar Morena San Carlos','2 kg',3.5,1000,'/OnlineShop/products-images/azucar-morena-san-carlos.jpg','San Carlos','Azúcar de caña poco refinada ideal para endulzar tus comidas'),
(NULL,'Azúcar Morena Valdez','5 kg',7,500,'/OnlineShop/products-images/azucar-san-carlos.jpg','Valdez','Azúcar de caña poco refinada ideal para endulzar tus comidas'),
(NULL,'Azúcar San Carlos','500 gr',1,2500,'/OnlineShop/products-images/azucar-morena-san-carlos.jpg','San Carlos','Azúcar de caña refinada ideal para endulzar tus comidas'),
(NULL,'Azúcar Valdez','1 kg',2.5,1500,'/OnlineShop/products-images/azucar-valdez.jpg','Valdez','Azúcar de caña refinada ideal para endulzar tus comidas'),
(NULL,'Salsa China de Soya','300 gr',3.5,2500,'/OnlineShop/products-images/china-oriental.webp','Oriental','Salsa china de Soya extraida de los cultivos mas productivos en China'),
(NULL,'Detergente Ciclón Líquido con Suavizante','2000 ml',7.2,500,'/OnlineShop/products-images/ciclon-suavizante.webp','Ciclón','Detergente líquido para todo tipo de ropa, con un toque de suavizante'),
(NULL,'Detergente Ciclón en Polvo con Suavizante','320 gr',0.75,2350,'/OnlineShop/products-images/ciclon-suavizante-polvo.jpg','Ciclón','Detergente en polvo para todo tipo de ropa, con un toque de suavizante'),
(NULL,'Colgate Luminous White','170 gr',3.5,1500,'/OnlineShop/products-images/colgate-luminous-white.jpg','Colgate','Pasta de Dientes con especial acción blanqueadora'),
(NULL,'Colgate Triple Acción','125 ml',1.75,2500,'/OnlineShop/products-images/colgate-triple-accion.jpg','Colgate','Pasta de dientes con especial acción de limpieza'),
(NULL,'Colgate Original','150 ml',1.5,1750,'/OnlineShop/products-images/colgate.webp','Colgate','Pasta de dientes con sabor neutro e ideal para cualquiera'),
(NULL,'Detergente Deja en Polvo Limón','5 kg',10.5,750,'/OnlineShop/products-images/deja-limon.webp','Deja','Detergente en polvo con aroma a Limón'),
(NULL,'Detergente Deja en Polvo Suavizante','5 kg',10.5,500,'/OnlineShop/products-images/deja-suavizante.jpg','Deja','Detergente en polvo con un toque de suavizante'),
(NULL,'Enjuague Bucal Gingivit','500 ml',2.75,2500,'/OnlineShop/products-images/enjuage-bucal-gingivit.jpg','Gingivit','Enjuague bucal con doble acción de limpieza'),
(NULL,'Queso Mascarpone Floralp','200 gr',2.5,700,'/OnlineShop/products-images/floralp-mascarpone.jpg','Floralp','Queso listo para recetas de postres'),
(NULL,'Fréjol Canario Facundo','425 gr',1.50,1750,'/OnlineShop/products-images/frejol-facundo.png','Facundo','Fréjol en lata para menestra listo para preparar'),
(NULL,'Menestra de Frejol Facundo','425 gr',2.25,1560,'/OnlineShop/products-images/frejol-rojo-facundo.jpg','Facundo','Menestra de Fréjol lista para servir'),
(NULL,'Harina Santa Lucía','50 kg',30.20,100,'/OnlineShop/products-images/harina-santalucia.png','Santa Lucía','Harina de Trigo para todo tipo de preparación'),
(NULL,'Harina YA','5 kg',2.65,1500,'/OnlineShop/products-images/harina-ya.jpg','YA','Harina de Trigo lista para todo tipo de preparación'),
(NULL,'Head & Shoulders Dermo Sensitive','375 ml',7.25,750,'/OnlineShop/products-images/h-s-dermo.jpg','head & shoulders','Shampoo para cabello con ph balanceado'),
(NULL,'Head & Shoulders Suave y Manejable','375 ml',7.25,750,'/OnlineShop/products-images/h-s-suave.webp','head & shoulders','Shampoo para cabello con suavizante'),
(NULL,'Salsa Inglesa McCormick','175 ml',2.75,2500,'/OnlineShop/products-images/inglesa-mc-cormic.jpg','McCormick','Salsa inglesa para aderezo de todo plato'),
(NULL,'Dove Delicious Care x4 Pack','400 gr',4.25,700,'/OnlineShop/products-images/jabon-dove-coco.jpg','Dove','Pack de 4 jabones de 100gr aroma de leche de Coco'),
(NULL,'Dove Revigorizante x4 Pack','360 gr',3.75,1500,'/OnlineShop/products-images/jabon-dove-revigor.webp','Dove','Pack de 4 jabones de 90gr aroma revitalizante'),
(NULL,'Dove Original','90 gr',1.05,2500,'/OnlineShop/products-images/jabon-dove.avif','Dove','Dove con aroma original para limpieza del cuerpo'),
(NULL,'Jolly Clásico','100 ml',1.5,1500,'/OnlineShop/products-images/jabon-jolly.png','Jolly','Jabón de manos con aroma purificante'),
(NULL,'Jolly Manzanilla','100 ml',1.5,1500,'/OnlineShop/products-images/jabon-jolly-manzanilla.png','Jolly','Jabón de manos con aroma a manzanilla'),
(NULL,'TRÜ Leche Entera','1 lt',1.12,1500,'/OnlineShop/products-images/leche-tru.jpg','TRÜ','Leche envasada en tetrapack 100% ecoamigable'),
(NULL,'Vita Leche Entera','500 ml',0.75,2500,'/OnlineShop/products-images/leche-vita.jpg','Vita','Leche envasada en funda plástica'),
(NULL,'Nutri Leche Entera','1 lt',1.16,2600,'/OnlineShop/products-images/leche-nutri-tetra.webp','Nutri','Leche envasada en tetrapack'),
(NULL,'Listerine Cuidado Total','500 ml',4.75,1750,'/OnlineShop/products-images/listerine-cuidado-total.png','Listerine','Enjuague bucal con acción refrescante'),
(NULL,'Facundo Maíz Dulce','425 gr',2.25,750,'/OnlineShop/products-images/maiz-facundo.png','Facundo','Maíz dulce enlatado listo para servir'),
(NULL,'Alacena Mayonesa','400 gr',4.5,1000,'/OnlineShop/products-images/mayonesa-alacena.png','Alacena','Mayonesa natural preparada como hecha en casa'),
(NULL,'Gustadina Mayonesa','200 gr',2.25,1250,'/OnlineShop/products-images/mayonesa-gustadina.webp','Gustadina','Mayonesa lista para acompañar cualquier preparación'),
(NULL,'Los Andes Mayonesa','200 ml',2.10,1370,'/OnlineShop/products-images/mayonesa-los-andes.webp','Los Andes','Mayonesa natural preparada como hecha en casa'),
(NULL,'Kiosko Queso Mozzarella','500 gr',3.5,750,'/OnlineShop/products-images/mozarella-kiosko.jpg','Kiosko','Queso Mozzarella ideal para fundir'),
(NULL,'Familia Papel Higiénico Megarollo','4 Rollos',4.5,1000,'/OnlineShop/products-images/papel-higienico-familia.jpg','Familia','Papel Higiénico Megarollo acolchaMAX'),
(NULL,'Hada Papel Higiénico Económico','6 Rollos',4.5,2500,'/OnlineShop/products-images/papel-higienico-hada.jpg','Hada','Papel Higiénico económico doble hoja y extra perfume'),
(NULL,'Scott Papel Higiénico Cuidado Completo','4 Rollos',3.75,1500,'/OnlineShop/products-images/papel-higienico-scott.jpg','Scott','Papel Higiénico cuidado completo corta fácil'),
(NULL,'Condimensa Paprika','100 gr',2.5,2600,'/OnlineShop/products-images/paprika.jpg','Condimensa','Paprika ideal para carnes, mariscos y sopas'),
(NULL,'Toni Queso Crema','600 gr',3.5,2000,'/OnlineShop/products-images/queso-toni.jpg','Toni','Queso crema listo para untar'),
(NULL,'Cris-Sal Sal de Mesa','500 gr',2.25,1750,'/OnlineShop/products-images/sal-cris-sal.png','Cris-Sal','Sal yodada y fluorurada'),
(NULL,'Condimensa Sal del Himalaya Molida','900 gr',3.5,1000,'/OnlineShop/products-images/sal-himalaya.jpg','Condimensa','Sal del Himalaya Molida con oligoelementos'),
(NULL,'Gustadina','350 gr',2.5,2500,'/OnlineShop/products-images/salsa-bbq.jpg','Gustadina','Salsa BBQ ideal para ahumados y asados'),
(NULL,'Gustadina Salsa Golf','200 gr',1.8,2600,'/OnlineShop/products-images/salsa-golf.webp','Gustadina','Salsa rosa para acompañar cocteles'),
(NULL,'Alacena Salsa de Tomate','200 ml',2.5,1000,'/OnlineShop/products-images/salsa-tomate-alacena.webp','Alacena','Salsa de tomate con preparación casera'),
(NULL,'Gustadina Salsa de Tomate','200 ml',3.25,2500,'/OnlineShop/products-images/salsa-tomate-gustadina.webp','Gustadina','Salsa de tomate rica en elicopeno'),
(NULL,'Los Andes Salsa de Tomate','200 ml',2.75,2500,'/OnlineShop/products-images/salsa-tomate-los-andes.webp','Los Andes','Salsa de tomate sin preservantes ni colorantes'),
(NULL,'Familia Servilletas Acolchamax','250 hojas',3.5,1500,'/OnlineShop/products-images/servilleta-familia.png','Familia','Servilleta mediana acolchamax para uso en cocina'),
(NULL,'Weir Cool Mint Enjuague Bucal','250 ml',4.5,1000,'/OnlineShop/products-images/weir-cool-mint.jpg','Weir','Enjuague bucal de limpieza dental profunda'),
(NULL,'Chivería Yogurt Natural','1600 gr',4.5,2000,'/OnlineShop/products-images/yogurt-chiveria-clasico.jpg','Chivería','Yogurt natural libre de conservantes y colorantes artificiales'),
(NULL,'Chivería Yogurt Durazno','900 gr',3.25,2000,'/OnlineShop/products-images/yogurt-chiveria-durazno.jpg','Chivería','Yogurt de durazno libre de conservantes y colorantes artificiales'),
(NULL,'Toni Yogurt Frutilla','900 gr',4.25,2600,'/OnlineShop/products-images/yogurt-toni-fresa.jpg','Toni','Yogurt de frutilla libre de conservantes y colorantes artificiales'),
(NULL,'Toni Yogurt Mora','900 gr',4.25,2600,'/OnlineShop/products-images/yogurt-toni-mora.jpg','Toni','Yogurt de mora libre de conservantes y colorantes artificiales');